export const SEARCH_KEYWORD = "SEARCH_KEYWORD"
export const TYPE_KEYWORD = "TYPE_KEYWORD"
export const FIND_MOVIES_BY_TITLE = "FIND_MOVIES_BY_TITLE"
export default {SEARCH_KEYWORD, TYPE_KEYWORD, FIND_MOVIES_BY_TITLE}